--- #Items which NPC is going to deposit into chests. Other items stay in its inventory.
items:
  - diamond
  - emerald_ore
  - lapis_lazuli
  - redstone
  - gold_ore
  - iron_ore
  - coal
  - gold_nugget

#Whether Hostile mobs will attack NPCs on sight. Only works when distance is <=10 blocks.
Monster_Hostility: true

#List of hostile monsters who are not going to attack NPCs
Hostile_Monster_Exceptions:
- enderman
- creeper


#Distance between strips when mining.
StripMineDistance: 2

#Dimensions of a single strip
Strip_Height: 2
Strip_Width: 2

#Whether NPC places torches upon mining.
Place_Torches: true

#Whether NPC places torches from its inventory or creates them from nothing. Has no effect if Place_Torches is false.
Place_Torches_from_Inventory: true

#Distance between torches put down by Miner NPC. Has no effect if Place_Torches is false.
TorchDistance: 1

#Amount of torches NPC tries to have before starting a new strip
PrefferedTorchAmount: 64

#Items which are not removed from NPCs inventory after depositing
ItemsNotToRemove:
  - torch
  - wooden_pickaxe