--- #Items which NPC is going to deposit into chests. Other items stay in its inventory.
items:
  - diamond
  - emerald_ore
  - lapis_ore
  - redstone
  - gold_ore
  - iron_ore
  - coal_ore
  - gold_nugget
